---
title: "Final Project Data"
output:
  pdf_document: default
  html_notebook: default
---

```{r}
library(mdsr)   # Load additional packages here
library(tidyverse)
library(plotly)
library(knitr)

# Some customization.  You can alter or delete as desired (if you know what you are doing).
trellis.par.set(theme=theme.mosaic()) # change default color scheme for lattice
knitr::opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small")
```


```{r}
library(readr)
outbreaks_dataset <- read_csv("data/outbreaks dataset.csv")
table(outbreaks_dataset$State)

outbreaks_tidy <- outbreaks_dataset %>%
  filter(Location == "Restaurant") 

outbreaks_by_state <- outbreaks_tidy %>%
  group_by(State, Year) %>%
  summarise(num_outbreaks = n(), num_hosp = sum(Hospitalizations, na.rm = T), num_ill = sum(Illnesses, na.rm = T), num_fatal = sum(Fatalities, na.rm = T)) %>%
  arrange(desc(num_outbreaks))

##time series plot
ggplot(outbreaks_by_state, aes(x = Year, y = num_outbreaks, col = State)) + geom_line()
```


```{r}
ecoli_data <- read_csv("data/ecoli filtered data.csv")
names(ecoli_data)

ecoli_clean <- ecoli_data %>%
  select(biosample_acc, collection_date, epi_type, geo_loc_name, host, isolation_source, target_creation_date, status)
```

```{r}
salmonella_1 <- read_csv("data/Salmonella Part 1.csv")
salmonella_2 <- read_csv("data/Salmonella Part 2.csv")

salmonella_dataset <- rbind(salmonella_1, salmonella_2)
names(salmonella_dataset)

salmonella_clean <- salmonella_dataset %>%
  select(biosample_acc, epi_type, geo_loc_name, host, scientific_name, sra_release_date, strain, target_creation_date, status, isolation_source, collection_date)
```

```{r}
#importing florida restaurant data
#for(month in c('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12')){
  #for(year in 10:15){
   # url <- sprintf('ftp://dbprftp.state.fl.us/pub/llweb/rdar%s%s.csv', month, year)
    #monthly_df <- read_csv(url, col_names=F)
    #write.csv(monthly_df, sprintf('data/florida_violation_%s_%s', month, year), row.names=F)
  #}
#}

current_bind <- rbind(read_csv('data/florida_violation_01_10'), read_csv('data/florida_violation_01_11'))

for(month in c('01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12')){
  for(year in 10:15){
  if((month != '01' & year != '10') & (month != '01' & year != '11')){
  str <- sprintf('data/florida_violation_%s_%s', month, year)
  current_bind <- rbind(current_bind, read_csv(str))
  }
  }
}

#not working right now
all_florida_restaurants <- current_bind
library(lubridate)

#restaurants <- all_florida_restaurants %>%
  #filter(!is.na(X11)) %>%
  #mutate(date = mdy(all_florida_restaurants$X11, format="%m/%d/%Y"))
         
#table(restaurants$date)
```

```{r}
library(zoo)
#outbreaks for florida
outbreaks_florida <- outbreaks_tidy %>%
  filter(State == "Florida", Year >= 2010) %>%  
  mutate(month_num = ifelse(Month == "January", 01, 
                            ifelse(Month == "February", 02, 
                                   ifelse(Month == "March", 03, 
                                          ifelse(Month == "April", 04,
                                                 ifelse(Month == "May", 05,
                                                        ifelse(Month == "June", 06,
                                                               ifelse(Month == "July", 07,
                                                                      ifelse(Month == "August", 08,
                                                                             ifelse(Month == "September", 09,
                                                                                    ifelse(Month == "October", 10,
                                                                                           ifelse(Month == "November", 11, 12))))))))))),
         date_char = paste(Year, month_num, sep="-"),
         yearmon_date = as.yearmon(date_char)) %>%
  group_by(State, yearmon_date) %>%
  summarise(num_outbreaks = n(), num_hosp = sum(Hospitalizations, na.rm = T), num_ill = sum(Illnesses, na.rm = T), num_fatal = sum(Fatalities, na.rm = T)) %>%
  arrange(desc(num_outbreaks))
  
ggplot(outbreaks_florida, aes(x = yearmon_date, y = num_outbreaks)) + geom_point() + geom_smooth(se = F)

ggplot(outbreaks_florida, aes(x = yearmon_date, y = num_outbreaks)) + geom_line() 
```

```{r}
#restaurant violations per year

violations_graph <- all_florida_restaurants %>%
  mutate(date = as.Date(X11, "%m/%d/%Y"), yearmon_flor = as.yearmon(date)) %>%
  group_by(yearmon_flor) %>%
  summarise(sum_violations = sum(as.numeric(X9), na.rm = T))

ggplot(data = violations_graph, aes(x = yearmon_flor, y = sum_violations)) + geom_line()

#ggplot() + geom_line(data = violations_graph, aes(x = yearmon_flor, y = sum_violations)) + geom_line(data = outbreaks_florida, aes(x = yearmon_date, y = num_outbreaks))


```

```{r}
combined_graph <- inner_join(outbreaks_florida, violations_graph, by = c("yearmon_date" = "yearmon_flor"))

ggplot(data = combined_graph, aes(x = sum_violations, y = num_outbreaks)) + geom_point() + geom_smooth(se = F)

ggplot(data = combined_graph, aes(x = sqrt(sum_violations), y = num_outbreaks)) + geom_point() + geom_smooth(se = F)

ggplot(data = combined_graph, aes(x = sqrt(sum_violations), y = num_outbreaks)) + geom_point() + geom_smooth(se = F) + xlim(20, 27)

cor(combined_graph$sum_violations, combined_graph$num_outbreaks, method = "pearson")
```

##Map

```{r}
library(maps)
library(RColorBrewer)
library(devtools)
library(gganimate)

outbreaks_data_for_map <- outbreaks_by_state %>%
  filter(Year >= 2000) %>%
  mutate(state_name = tolower(State), bi_year = 2 * floor(Year/2))

all_states <- map_data("state")

outbreaks_map <- right_join(outbreaks_data_for_map, all_states, by = c("state_name" = "region"))

outbreaks_map$VALUE <- outbreaks_map$num_outbreaks

 p <- ggplot() + geom_polygon(data=outbreaks_map, aes(x=long, y=lat, group = group, fill=VALUE, frame = bi_year, cumulative = F), colour="white") + xlab("Longitude") + ylab("Latitude") + theme(plot.title = element_text(hjust = 0.5, face = "bold")) + scale_fill_gradient(low = "white", high = "red", na.value = "grey80") 


gganimate(p, title_frame = F)

#gganimate(p, filename = "maptimeseries",  saver = "gif", interval = 3.0)

aq <- airquality
aq$date <- as.Date(paste(1973, aq$Month, aq$Day, sep = "-"))

p2 <- ggplot(aq, aes(date, Temp, frame = Month, cumulative = TRUE)) +
  geom_line()

gganimate(p2, title_frame = FALSE)

library(animation)
saveGIF({

  for (i in unique(outbreaks_map$bi_year)) {

    data <- subset(outbreaks_map, bi_year == i)
    p <- ggplot() + geom_polygon(data=outbreaks_map, aes(x=long, y=lat, group = group, fill=VALUE, colour="white")) + xlab("Longitude") + ylab("Latitude") + theme(plot.title = element_text(hjust = 0.5, face = "bold")) + scale_fill_gradient(low = "white", high = "blue", na.value = "grey80") + ggtitle(i)

    print(p)                      

  }
}, movie.name = "map.gif", interval = 0.2)


saveGIF({
  brownian.motion(pch = 21, cex = 5, col = "red", bg = "yellow")
}, movie.name = "brownian_motion.gif", interval = 0.1, nmax = 30, 
  ani.width = 600)

im.convert(p, output = "animation.gif", convert = c("convert", "gm convert"), 
    cmd.fun = if (.Platform$OS.type == "windows") shell else system, extra.opts = "", 
    clean = FALSE)
gm.convert(..., convert = "gm convert")


system("convert -delay 80 *.png brownian_motion.gif")
```


```{r}
#poultryfoods <- c("Chicken")
#meatfoods <- c("Wings", "Ham", "Meatball")
#fishfoods <- c("Sushi")

d <- outbreaks_tidy %>%
  filter(Year >= 2013, !is.na(Food)) %>%
  mutate(poultry = ifelse(grepl("Chicken|Duck", as.character(Food)), 1, 0),
    meat = ifelse(grepl("Wings|Ham|Meatball|Sausage|Steak|Beef|Burger|Pork|burger|Bacon", as.character(Food)), 1, 0), 
    fish = ifelse(grepl("Sushi|Oysters|Fish|Kare|Crab|fish|Tuna|Shrimp|Scallops|Salmon|Seafood|Clam|Lobster|Eel", as.character(Food)), 1, 0),
    veggie = ifelse(grepl("Salad|Tomato|Lettuce|Pepper|Broccoli|Carrot|Bean|Cabbage|Onion|Vegetable|Guacamole|Cucumber|Zucchini", as.character(Food)), 1, 0),
    carbs = ifelse(grepl("Roll|Bread|Fries|Rice|Noodles|Pizza|Pancake|Pasta", as.character(Food)), 1, 0),
    dairy = ifelse(grepl("Goat|Cream|Egg|Cheese|Alfredo|Mozzarella|Provolone", as.character(Food)), 1, 0),
    dessert = ifelse(grepl("Pie|Cookie|Brownie|Pastry", as.character(Food)), 1, 0)
         )

#d %>% select(Food, meat, fish) %>% head()

quizfoods <- d %>%
  group_by(State) %>%
  summarise(total_poultry = sum(poultry), total_meat = sum(meat), total_fish = sum(fish), total_veggie = sum(veggie), total_carbs = sum(carbs), total_dairy = sum(dairy), total_dessert = sum(dessert), total_outbreaks = n())

statefooddata <- function(state){
  foods_state<- quizfoods%>% 
    filter(State == state)
  paste("Number of total outbreaks: ", foods_state$total_outbreaks)
  p
}

statefooddata("Massachusetts")

```

```{r}
ui <- fluidPage(
  title = "Dangerous Foods in Your State",
  sidebarLayout(
    sidebarPanel(
      selectizeInput(
        'e0', 'Select Your State',
        choices = quizfoods$State
      ),
      selectizeInput(
        'e1', 'Food Preferences', choices = c("Poultry", "Meat", "Fish", "Vegetables", "Carbs", "Dairy", "Desserts"), multiple = T
      )
    ),
  mainPanel(
    helpText("Foods to Avoid"),
    verbatimTextOutput("result")
      )
  
)
)

server <- function(input, output, session) {
    output$result <- renderPrint({
      result <- paste("Hi", statefooddata(input$e0))
      result
      }
)
}
food_quiz <- shinyApp(ui, server)
runApp(food_quiz)
```

    